server:
  port: 3333
spring:
  application:
    name: s4c-microservice-data-visualization
#    jpa:
#      database: MYSQL
#      show-sql: true
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#        ddl-auto: validate
#    datasource:
#      platform: mysql
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/data_visualization
#      usernme : root
#      password: rod436tr

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 11
  client:
    serviceUrl:
      defaultZone: http://us1.fiwoo.eu:3331/eureka/
    healthcheck:
      enabled: true
    lease: null
duration: 5
logging:
  file: logs/${spring.application.name}.log
  level:
    org.springframework.cloud: DEBUG