server:
  port: 8080 
spring:
  application:
    name: s4c-microservice-data-visualization
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 11
  client:
    serviceUrl:
      defaultZone: http://dev-sac-fase-dos-eureka-registry.emergyalabs.com:8080/eureka/
    healthcheck:
      enabled: true
    lease: null
duration: 5
logging:
  file: logs/${spring.application.name}.log
  level:
    org.springframework.cloud: DEBUG
